### ISSUE TITLE
Can't seem to change settings

### ISSUE THREAD

**Issue by krugster** [OstlerDev/PopcornTV#172]
With the latest (awesome!) changes to the settings page, I can't seem to actually switch between the desired quality settings for example

**Comment by OstlerDev** [comment]
I will take a look at this in the morning :)

**Comment by OstlerDev** [comment]
I believe this is fixed @krugster if it is not let me know!

**Comment by krugster** [comment]
Sorry, it looks like it's not fixed still.  I did a "git pull", "npm install", and restarted the app...my settings still seem locked, I can't click on or change anything.

**Comment by OstlerDev** [comment]
How are you running PopcornTV? Are you running it via a daemon?

I pushed up more changes today that further fix the issue with them being stuck, can you post a full debug log?

**Comment by krugster** [comment]
Never mind, it's working now!

**Comment by OstlerDev** [comment]
Awesome! Glad that it is working for you now :)
