### ISSUE TITLE
Crash on starting stream

### ISSUE THREAD

**Issue by seeitbelieveit** [OstlerDev/PopcornTV#59]
Trying to start true detective s2e1 and had two crashes in a row.

https://gist.github.com/seeitbelieveit/d34ace25d1e7fd506bf8

**Comment by OstlerDev** [comment]
I just pushed up a commit, can you pull down the latest and test it to see if that works for you?

**Comment by seeitbelieveit** [comment]
Same crash

**Comment by OstlerDev** [comment]
This should fix the issue for you, please test again.

**Comment by seeitbelieveit** [comment]
I'm using git fetch, last update had 3 changes, but it still crashed.

**Comment by OstlerDev** [comment]
I tested that episode on my local setup and it worked fine, try using `git pull`

**Comment by seeitbelieveit** [comment]
ok, it worked

**Comment by OstlerDev** [comment]
Glad to hear! Enjoy!

**Comment by seeitbelieveit** [comment]
Were you actually able to get it to play? 
I get 
Debug: [0%] Downloaded 0.02MB - 0MB/s | Peers: 0 Seeds: 0 | ETA: 10551m
Then "Trailer is unavailable. Try again later."

**Comment by OstlerDev** [comment]
That issue occurs because there is not enough seeders for the torrent. Right now there is a bug ( #2 ) where if 2MB is not downloaded before 60 seconds have elapsed then the stream fails.

So if there are not enough seeders or you have too slow of a connection it can happen. I am able to stream it just fine however, so it might be an issue with your download connection.

```
Streamer: Streamer: Starting Stream... Please wait for stream to be ready.
Web: /Movies/MoviePlay.xml
Debug: [0%] Downloaded 0.02MB - 0MB/s | Peers: 0 Seeds: 26 | ETA: 1886.9m
Debug: [0%] Downloaded 0.25MB - 0.05MB/s | Peers: 0 Seeds: 26 | ETA: 144.1m
Debug: [0%] Downloaded 0.5MB - 0.08MB/s | Peers: 0 Seeds: 27 | ETA: 81.8m
Debug: [0%] Downloaded 0.75MB - 0.11MB/s | Peers: 0 Seeds: 27 | ETA: 61m
Debug: [0%] Downloaded 1MB - 0.13MB/s | Peers: 0 Seeds: 26 | ETA: 50.6m
Debug: [0%] Downloaded 1.25MB - 0.16MB/s | Peers: 0 Seeds: 26 | ETA: 41.8m
Debug: [0%] Downloaded 1.5MB - 0.18MB/s | Peers: 0 Seeds: 26 | ETA: 37m
Debug: [0%] Downloaded 1.75MB - 0.19MB/s | Peers: 0 Seeds: 26 | ETA: 33.5m
Streamer: Ready to Stream, binding to http://10.0.1.2:9999
Debug: === Ending MoviePlay.xml Generation ===
Debug: <?xml version="1.0" encoding="UTF-8"?>
<atv><body><videoPlayer id="com.sample.video-player"><httpFileVideoAsset id="The Western Book of the Dead"><mediaURL>http://10.0.1.2:9999/tt2356777.mp4</mediaURL><title>The Western Book of the Dead</title><description>The disappearance of a city manager disrupts a lucrative land scheme and ignites an investigation involving three police officers and a career criminal who is moving into legitimate business.</description><image>https://walter.trakt.us/images/episodes/001/824/750/screenshots/thumb/66789d95b4.jpg</image><videoPlayerSettings><subtitleSize>100</subtitleSize></videoPlayerSettings><myMetadata><subtitleURL>http://trailers.apple.com/subtitle.json?url=Off</subtitleURL></myMetadata></httpFileVideoAsset></videoPlayer></body></atv>
Debug: [1%] Downloaded 2MB - 0.22MB/s | Peers: 0 Seeds: 26 | ETA: 30.1m
Debug: Query: {"level":"Debug","log":"willStartPlaying/getVideoPlayerSettings done"}
Debug: Query: {"url":"Off"}
Web: /subtitle.json
Debug: trailers.apple.com change to 10.0.1.2
Debug: Query: {"level":"Debug","log":"updateMetadata done"}
Debug: Query: {"level":"Debug","log":"subtitleURL: http://trailers.apple.com/subtitle.json?url=Off"}
Debug: Query: {"level":"Debug","log":"updateMetadata/getMetadata done"}
Debug: Query: {"level":"Debug","log":"willStartPlaying/parseSubtitleJSON done"}
Debug: Query: {"level":"Debug","log":"willStartPlaying done"}
Debug: Query: {"level":"Debug","log":"willStartPlaying/createSubtitleView done"}
Debug: [1%] Downloaded 2.25MB - 0.23MB/s | Peers: 0 Seeds: 26 | ETA: 28.2m
Debug: Query: {"level":"Debug","log":"[object Object]"}
Debug: [1%] Downloaded 2.5MB - 0.24MB/s | Peers: 0 Seeds: 26 | ETA: 26.7m
Debug: [1%] Downloaded 2.75MB - 0.26MB/s | Peers: 0 Seeds: 25 | ETA: 24.9m
Debug: [1%] Downloaded 3.25MB - 0.3MB/s | Peers: 0 Seeds: 25 | ETA: 22m
Debug: [1%] Downloaded 3.75MB - 0.33MB/s | Peers: 0 Seeds: 25 | ETA: 19.5m
Debug: [1%] Downloaded 4MB - 0.35MB/s | Peers: 0 Seeds: 25 | ETA: 18.6m
```

**Comment by seeitbelieveit** [comment]
That's possible, but I normally get about 6.5 MB/s on torrents and others don't seem to have a problem. 

Just tried it again, after about 4 tries the torrent started downloading.

**Comment by OstlerDev** [comment]
Hmm, thats a weird issue, I will keep an eye on it.

**Comment by seeitbelieveit** [comment]
Now it shows unsupported file type, but that's another issue not related.

**Comment by seeitbelieveit** [comment]
then crashed 

https://gist.github.com/seeitbelieveit/785cf3d699fce1d73f66

**Comment by seeitbelieveit** [comment]
not sure what changed, but getting a lot of unsupported messages on other tv episodes, (.mkv/webm)

**Comment by OstlerDev** [comment]
Try changing the quality to 480p. I find that for TV shows the 480p one is usually an mp4.

As for that error, I recently implemented that to notify users. Currently we are only able to stream .mp4, .m4v and .mov files. This is a restriction with the Apple TV hardware.

**Comment by seeitbelieveit** [comment]
Is there no way to filter by file type on the site you're pulling from?

**Comment by OstlerDev** [comment]
Sadly, no. There is no way to see the file type with the site I am using (eztvapi.re). That is why that error is only thrown after 2MB has been downloaded so I can run a filetype check on the file.

Right now the only way around the unsupported file type is to convert it while its being downloaded. I have a plan for this using FFMPEG, but that will need to wait for another day. (Watch #3 for more information)

**Comment by seeitbelieveit** [comment]
Do you have a channel setup on freenode to chat?

**Comment by OstlerDev** [comment]
I just created the room #PopcornTV on Freenode, feel free to join it.
