### ISSUE TITLE
"http://trailers.apple.com/trailers.cer" 404ed 

### ISSUE THREAD

**Issue by rjrobinson** [OstlerDev/PopcornTV#99]
So I guess apple has removed this. I tried my own workaround by generating some certs like the do for Plex... However.. When I go to add profile... Im not sure what to exactly place in there. 

I have tried to place my current IP with the path to the assets/certs folder, but that didnt work. 

Thoughts?

**Comment by OstlerDev** [comment]
You need to place the certificates that you generate in "assets/certificates/".

**Comment by rjrobinson** [comment]
I disagree. 
 when I enter the site "http://trailers.apple.com/trailers.cer" into the add profile. If throws an error. 

I generated the certs and placed them in the correct folder. 

I also tried ' https:// ' and just ' :// ' 

When I nav to Trailers on my Apple TV it says "Trailers are not available at this time. ' I also tried to install the cert with Apple Configurator and got the same error. 

ideas?

**Comment by OstlerDev** [comment]
What is the error you are getting on the Apple TV? Can you post your full log of Popcorn TV?

Also, if you are on a Mac, just let it generate the certificate for you, this is the easiest way to make sure that it was generated correctly.

**Comment by rjrobinson** [comment]
Ok. I go through the set as per the Mac instructions. I get to step 8 on the AppleTV and enter "http://trailers.apple.com/trailers.cer" into the address bar, press Submit. The AppleTV says that there was an "error not found"

I generated it with a mac as well. Through the command line. Copied the files into their respective folders.

**Comment by OstlerDev** [comment]
Try erasing the certificates you generated and let them generate themselves.

**Comment by rjrobinson** [comment]
When you say "generate themselves", do you mean to say step 8, where I enter the /trailers.cer address under the "Add Profile" page?

**Comment by OstlerDev** [comment]
Try deleting the certificates that you placed in ``assets/certificates/`` then running PopcornTV. The program generates the certificates you need with the encoding needed. It could also be that you either did not change the DNS or are not running PopcornTV at the time that you try to add the profile.

You need to run PopcornTV at all times when using the application.

**Comment by rjrobinson** [comment]
Changed the DNS settings. I have PopcornTV running. I deleted the certs and re generated them through the app. I have deleted the whole project, and re did the process from the beginning. The entire thing.  When i go to the Add Profile Section I get the following error. 

``` 
Unable to add Profile. An Error occurred while adding the profile [109]. Check the URL and try again.
 ```

**Comment by OstlerDev** [comment]
Can you post your entire terminal log?

**Comment by rjrobinson** [comment]
```
 RJ@rjOS:~/Dropbox/PopcornTV|master⚡⇒  sudo node atv.js
notice: Starting PopcornTV
DNS: DnsProxy binding on 10.0.1.25:53
Web: listening on 10.0.1.25:80
Web: SSL Web: listening on 10.0.1.25:443
DNS: bookkeeper.itunes.apple.com
DNS: upp.itunes.apple.com
DNS: mesu.apple.com
```

**Comment by OstlerDev** [comment]
It looks like your DNS settings are ok, but it is not sending the certificate.

Try entering in ``10.0.1.25/trailers.cer`` and see if that works

**Comment by rjrobinson** [comment]
reset router and got 
```RJ@rjOS:~/Dropbox/PopcornTV|master⚡⇒  sudo node atv.js
notice: Starting PopcornTV
DNS: DnsProxy binding on 10.0.1.25:53
Web: listening on 10.0.1.25:80
Web: SSL Web: listening on 10.0.1.25:443
DNS: bookkeeper.itunes.apple.com
DNS: upp.itunes.apple.com
DNS: mesu.apple.com
DNS: local
DNS: iadsdk.apple.com
DNS: www.apple.com
DNS: init-p01st.push.apple.com
DNS: cl5.apple.com
DNS: 45-courier.push.apple.com
DNS: p3-buy.itunes.apple.com
DNS: itunes.apple.com```

trying the 10.0.1.25/trailers.cer now

**Comment by rjrobinson** [comment]
Still getting the same error.

**Comment by OstlerDev** [comment]
Are you seeing anything at all more in the terminal window?

**Comment by rjrobinson** [comment]
Same output as before. Should I try and totally reset my appleTV?

**Comment by OstlerDev** [comment]
That might help, try that and start again from scratch.

**Comment by masonjames** [comment]
Also, just curious, are you running this in debug mode using `sudo node atv.js Debug' ?

**Comment by OstlerDev** [comment]
I just pushed up an update @rjrobinson I think your issue might have been that you were referencing the file from outside the folder. Regardless, please try updating to the latest version and try again.

**Comment by OstlerDev** [comment]
@rjrobinson if your issue is not resolved please feel free to comment and I will reopen this.

**Comment by juanjoseixas** [comment]
Same issue here; resetting the Apple TV doesn't fix the problem

**Comment by juanjoseixas** [comment]
My log: https://gist.github.com/juanjoseixas/7797f44580b7b961a9f7

**Comment by OstlerDev** [comment]
@juanjoseixas When you open the trailers application do you get an error, or does it go to the Trailers Application?

It looks like your DNS has changed over on your Apple TV, but for some reason is just not wanting to work for you.

**Comment by juanjoseixas** [comment]
I get this error when I open the trailers app: "Trailers is unavailable. Try again later."
